[tool.poetry]
name = "makru_langc_new"
version = "0.1.0-alpha.0"
description = "a mini program to create directory layout for c project using makru_langc"
authors = ["thisLight <l1589002388@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.7, <4"
clint = "^0.5.1"
makru = "^0.1.0-rc.3"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"

[tool.poetry.scripts]
makru_langc_new="makru_langc_new:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
