[tool.poetry]
name = "django-model-mail"
version = "0.3.0"
description = "Django package that helps to create emails from models (e.g. for admins' notifications)"
authors = ["Anatoly Gusev <gusev.tolia@yandex.ru>"]
license = "MIT"
readme = "README.rst"
keywords = ["django-model-mail"]
repository = "https://github.com/la1t/django-model-mail"
packages = [
    { include = "model_mail" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/la1t/django-model-mail/issues"
"Source" = "https://github.com/la1t/django-model-mail"
"Documentation" = "https://django-model-mail.readthedocs.io"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.0.0"

[tool.poetry.dev-dependencies]
pip = "^19.2.3"
wheel = "^0.36.2"
flake8 = "^3.9.0"
tox = "^3.23.0"
pytest = "^6.2.2"
pre-commit = "^2.11.1"
mypy = "^0.812"
black = "^20.8b1"
coverage = "^5.5"
pytest-cov = "^2.11.1"
pytest-django = "^4.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
