[tool.poetry]
name = "syneto_api"
version = "0.1.0"
description = "Syneto Client API library"
authors = ["Your Name <you@example.com>"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.6"
python-dotenv = "^0.16.0"
requests = {extras = ["secure"], version = "^2.25.1"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
ipdb = "^0.13.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
