[tool.poetry]
name = "afsql"
version = "0.1.2"
description = ""
authors = ["Asdil"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
PyMySQL = "^1.0.2"
DBUtils = "^2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
