[tool.poetry]
name = "olxbrasil"
version = "0.1.2"
description = "Biblioteca para scrapping da Olx Brasil (olx.com.br)"
authors = ["Marcelo Lino <mdslino@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
beautifulsoup4 = "^4.9.3"
httpx = "^0.17.0"
fake-useragent = "^0.1.11"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
ipython = "^7.21.0"
respx = "^0.16.3"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'