[tool.poetry]
name = "fetch-embed"
version = "0.1.0"
description = ""
authors = ["freemt <yucongo+fmt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.17.1"
alive-progress = "^1.6.2"
logzero = "^1.7.0"
numpy = "^1.20.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
