[tool.poetry]
name = "lwh"
version = "0.0.14"
description = "Lacework Helios Project cli"
authors = ["jeffthorne <jthorne@u.washington.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
lwh = "lwh.main:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.3.2"}
Jinja2 = "^2.11.3"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
